#!/usr/bin/env bash
# =============================================================================
# FairyZero — cache a prebuilt Linux engine on Google Drive so later Colab
# sessions SKIP the meson/ninja build AND the ONNX Runtime download.
# Companion to colab_setup.sh.
#
#   # ONCE — right after colab_setup.sh has built successfully:
#   !bash <bundle>/scripts/colab_prebuilt.sh save
#
#   # EVERY later session — instead of colab_setup.sh (takes seconds, no build):
#   !bash <bundle>/scripts/colab_prebuilt.sh restore
#   # then ALWAYS run the engine through the generated wrapper (it sets the
#   # library paths, which a bare `!cell` would otherwise lose):
#   !bash /content/FairyZero/engine_src/run.sh --selfplay --games 1000 ...
#   !bash /content/FairyZero/engine_src/run.sh --arena --model-a ... --model-b ...
#
# What gets cached (to $FZ_CACHE, default /content/drive/MyDrive/FairyZero_prebuilt):
#   * build-linux/custom_engine     — the compiled binary
#   * third_party/<ORT_PKG>/        — the ONNX Runtime libs the binary links to
#   * manifest.txt                  — ORT pkg + glibc, for a sanity note
#
# Override the cache location or ORT version like colab_setup.sh:
#   FZ_CACHE=/content/drive/MyDrive/my_cache  ORT_VER=1.18.0  bash <script> save
#
# WHEN A REBUILD IS STILL NEEDED (rare — `restore` will tell you):
#   * Colab changed its base image (glibc/Ubuntu) -> the binary won't start.
#   * Colab changed its CUDA MAJOR version        -> the CUDA EP won't load
#     (CPU mode still works). ORT 1.20.1 = CUDA 12; ORT 1.18.0 = CUDA 11.8.
#   In either case: run colab_setup.sh once more, then `save` again.
# =============================================================================
set -e

ACTION="${1:-restore}"
ORT_VER="${ORT_VER:-1.20.1}"
ORT_PKG="${ORT_PKG:-onnxruntime-linux-x64-gpu-${ORT_VER}}"
FZ_CACHE="${FZ_CACHE:-/content/drive/MyDrive/FairyZero_prebuilt}"

# --- locate the source tree (same auto-detect as colab_setup.sh) -------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
if   [ -f "$ROOT_DIR/meson.build" ];            then ENGINE_DIR="$ROOT_DIR"
elif [ -f "$ROOT_DIR/engine_src/meson.build" ]; then ENGINE_DIR="$ROOT_DIR/engine_src"
else echo "[prebuilt] FATAL: meson.build not found under $ROOT_DIR or $ROOT_DIR/engine_src"; exit 1; fi
echo "[prebuilt] engine dir: $ENGINE_DIR"
echo "[prebuilt] cache dir:  $FZ_CACHE"
echo "[prebuilt] ORT pkg:    $ORT_PKG"

# Write a run wrapper that sets LD_LIBRARY_PATH (ORT libs + Colab's CUDA libs)
# then execs the engine. Each Colab `!cell` is a fresh shell, so exporting env
# from this script would NOT survive to the next cell — the wrapper fixes that.
write_wrapper() {
  local wrap="$ENGINE_DIR/run.sh"
  cat > "$wrap" <<EOF
#!/usr/bin/env bash
# Auto-generated by colab_prebuilt.sh. Runs the prebuilt FairyZero engine with
# the right library paths. Usage: bash run.sh <engine args...>
ED="$ENGINE_DIR"
export LD_LIBRARY_PATH="\$ED/third_party/$ORT_PKG/lib:\${LD_LIBRARY_PATH:-}"
# CUDA EP needs Colab's CUDA libs (libcublasLt.so.12, libcudnn.so.9, ...): they
# ship inside torch's nvidia-* pip packages and /usr/local/cuda.
PYSITE="\$(python -c 'import site;print(site.getsitepackages()[0])' 2>/dev/null || echo '')"
if [ -n "\$PYSITE" ]; then
  for d in "\$PYSITE"/nvidia/*/lib; do [ -d "\$d" ] && export LD_LIBRARY_PATH="\$d:\$LD_LIBRARY_PATH"; done
fi
[ -d /usr/local/cuda/lib64 ] && export LD_LIBRARY_PATH="/usr/local/cuda/lib64:\$LD_LIBRARY_PATH"
exec "\$ED/build-linux/custom_engine" "\$@"
EOF
  chmod +x "$wrap"
  echo "[prebuilt] wrote wrapper: $wrap"
}

_copy_tree() {  # rsync if present (fast, skips unchanged), else plain cp -r
  local src="$1" dst="$2"
  rsync -a "$src/" "$dst/" 2>/dev/null || { mkdir -p "$(dirname "$dst")"; cp -rf "$src" "$(dirname "$dst")/"; }
}

case "$ACTION" in
  save)
    BIN="$ENGINE_DIR/build-linux/custom_engine"
    [ -x "$BIN" ] || { echo "[prebuilt] FATAL: no binary at $BIN — run colab_setup.sh first."; exit 1; }
    [ -d "$ENGINE_DIR/third_party/$ORT_PKG" ] || { echo "[prebuilt] FATAL: ORT pkg missing: third_party/$ORT_PKG"; exit 1; }
    mkdir -p "$FZ_CACHE/build-linux"
    cp -f "$BIN" "$FZ_CACHE/build-linux/custom_engine"
    _copy_tree "$ENGINE_DIR/third_party/$ORT_PKG" "$FZ_CACHE/third_party/$ORT_PKG"
    { echo "ort_pkg=$ORT_PKG";
      echo "glibc=$(ldd --version 2>/dev/null | head -1)";
      echo "saved=$(date)"; } > "$FZ_CACHE/manifest.txt"
    echo "[prebuilt] SAVED -> $FZ_CACHE  (custom_engine + $ORT_PKG)."
    echo "[prebuilt] Next sessions just: bash $SCRIPT_DIR/colab_prebuilt.sh restore"
    ;;

  restore)
    [ -x "$FZ_CACHE/build-linux/custom_engine" ] || {
      echo "[prebuilt] no cache at $FZ_CACHE."
      echo "[prebuilt] Build once with colab_setup.sh, then: colab_prebuilt.sh save"; exit 1; }
    mkdir -p "$ENGINE_DIR/build-linux"
    cp -f "$FZ_CACHE/build-linux/custom_engine" "$ENGINE_DIR/build-linux/custom_engine"
    chmod +x "$ENGINE_DIR/build-linux/custom_engine"
    if [ ! -d "$ENGINE_DIR/third_party/$ORT_PKG" ]; then
      _copy_tree "$FZ_CACHE/third_party/$ORT_PKG" "$ENGINE_DIR/third_party/$ORT_PKG"
    fi
    write_wrapper
    # Light Python deps for the training/seed scripts (torch is preinstalled).
    pip install -q onnx onnxruntime 2>/dev/null || true
    # Health check: CPU-only engine logic, no GPU needed.
    echo "[prebuilt] health check: --test-uci ..."
    if bash "$ENGINE_DIR/run.sh" --test-uci 2>/tmp/fz_health | grep -q '\[PASS\]'; then
      echo "[prebuilt] OK — prebuilt engine runs on this Colab image."
      echo "[prebuilt] You can SKIP colab_setup.sh. Run the engine via:"
      echo "           bash $ENGINE_DIR/run.sh <args>"
    else
      echo "[prebuilt] !! cached binary did NOT run here (Colab image likely changed)."
      echo "[prebuilt] !! See /tmp/fz_health. Fix: run colab_setup.sh once, then 'save' again."
      exit 1
    fi
    ;;

  *)
    echo "usage: colab_prebuilt.sh [save|restore]   (default: restore)"; exit 1;;
esac
