#!/usr/bin/env bash
# =============================================================================
# FairyZero — reuse a prebuilt Linux engine across Colab sessions so they SKIP
# the meson/ninja build AND the ONNX Runtime download. Companion to colab_setup.sh.
#
# TWO equivalent workflows — pick one:
#
# (1) SEPARATE CACHE on Drive (keeps the bundle source-only):
#   !bash <bundle>/scripts/colab_prebuilt.sh save      # once, after a build
#   !bash <bundle>/scripts/colab_prebuilt.sh restore   # every later session
#
# (2) BUILD INTO THE BUNDLE (the binary travels inside the bundle itself):
#   # once: build on local disk, then copy the artifacts back into the Drive bundle
#   !bash /content/FairyZero/scripts/colab_setup.sh
#   !cp -r /content/FairyZero/engine_src/build-linux /content/drive/MyDrive/FairyZero/engine_src/
#   !cp -r /content/FairyZero/engine_src/third_party /content/drive/MyDrive/FairyZero/engine_src/
#   # every later session: copy the bundle to local (binary included), then:
#   !bash /content/FairyZero/scripts/colab_prebuilt.sh wrap
#
#   # BOTH workflows: then run the engine through the generated wrapper (it sets the
#   # library paths, which a bare `!cell` would otherwise lose):
#   !bash /content/FairyZero/engine_src/run.sh --selfplay --games 1000 ...
#   !bash /content/FairyZero/engine_src/run.sh --arena --model-a ... --model-b ...
#
# What gets cached (to $FZ_CACHE, default /content/drive/MyDrive/FairyZero_prebuilt):
#   * build-linux/custom_engine     — the compiled binary
#   * third_party/<ORT_PKG>/        — the ONNX Runtime libs the binary links to
#   * manifest.txt                  — ORT pkg + glibc, for a sanity note
#
# Override the cache location or ORT version like colab_setup.sh:
#   FZ_CACHE=/content/drive/MyDrive/my_cache  ORT_VER=1.18.0  bash <script> save
#
# WHEN A REBUILD IS STILL NEEDED (rare — `restore` will tell you):
#   * Colab changed its base image (glibc/Ubuntu) -> the binary won't start.
#   * Colab changed its CUDA MAJOR version        -> the CUDA EP won't load
#     (CPU mode still works). ORT 1.20.1 = CUDA 12; ORT 1.18.0 = CUDA 11.8.
#   In either case: run colab_setup.sh once more, then `save` again.
# =============================================================================
set -e

ACTION="${1:-restore}"
ORT_VER="${ORT_VER:-1.20.1}"
ORT_PKG="${ORT_PKG:-onnxruntime-linux-x64-gpu-${ORT_VER}}"
FZ_CACHE="${FZ_CACHE:-/content/drive/MyDrive/FairyZero_prebuilt}"

# --- locate the source tree (same auto-detect as colab_setup.sh) -------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
if   [ -f "$ROOT_DIR/meson.build" ];            then ENGINE_DIR="$ROOT_DIR"
elif [ -f "$ROOT_DIR/engine_src/meson.build" ]; then ENGINE_DIR="$ROOT_DIR/engine_src"
else echo "[prebuilt] FATAL: meson.build not found under $ROOT_DIR or $ROOT_DIR/engine_src"; exit 1; fi
echo "[prebuilt] engine dir: $ENGINE_DIR"
echo "[prebuilt] cache dir:  $FZ_CACHE"
echo "[prebuilt] ORT pkg:    $ORT_PKG"

# Write a run wrapper that sets LD_LIBRARY_PATH (ORT libs + Colab's CUDA libs)
# then execs the engine. Each Colab `!cell` is a fresh shell, so exporting env
# from this script would NOT survive to the next cell — the wrapper fixes that.
write_wrapper() {
  local wrap="$ENGINE_DIR/run.sh"
  cat > "$wrap" <<EOF
#!/usr/bin/env bash
# Auto-generated by colab_prebuilt.sh. Runs the prebuilt FairyZero engine with
# the right library paths. Usage: bash run.sh <engine args...>
ED="$ENGINE_DIR"
export LD_LIBRARY_PATH="\$ED/third_party/$ORT_PKG/lib:\${LD_LIBRARY_PATH:-}"
# CUDA EP needs Colab's CUDA libs (libcublasLt.so.12, libcudnn.so.9, ...): they
# ship inside torch's nvidia-* pip packages and /usr/local/cuda.
PYSITE="\$(python -c 'import site;print(site.getsitepackages()[0])' 2>/dev/null || echo '')"
if [ -n "\$PYSITE" ]; then
  for d in "\$PYSITE"/nvidia/*/lib; do [ -d "\$d" ] && export LD_LIBRARY_PATH="\$d:\$LD_LIBRARY_PATH"; done
fi
[ -d /usr/local/cuda/lib64 ] && export LD_LIBRARY_PATH="/usr/local/cuda/lib64:\$LD_LIBRARY_PATH"
exec "\$ED/build-linux/custom_engine" "\$@"
EOF
  chmod +x "$wrap"
  echo "[prebuilt] wrote wrapper: $wrap"
}

# Wrapper + light Python deps + a health check against the in-place binary.
finish_local() {
  chmod +x "$ENGINE_DIR/build-linux/custom_engine" 2>/dev/null || true
  write_wrapper
  # torch is preinstalled on Colab; the train/seed scripts also import these.
  pip install -q onnx onnxruntime 2>/dev/null || true
  echo "[prebuilt] health check: --test-uci ..."
  if bash "$ENGINE_DIR/run.sh" --test-uci 2>/tmp/fz_health | grep -q '\[PASS\]'; then
    echo "[prebuilt] OK — engine runs on this Colab image. SKIP colab_setup.sh."
    echo "[prebuilt] Run the engine via:  bash $ENGINE_DIR/run.sh <args>"
  else
    echo "[prebuilt] !! engine did NOT run here (Colab image likely changed; see /tmp/fz_health)."
    echo "[prebuilt] !! Fix: run colab_setup.sh once to rebuild (then 'save' if you cache to Drive)."
    exit 1
  fi
}

_copy_tree() {  # rsync if present (fast, skips unchanged), else plain cp -r
  local src="$1" dst="$2"
  rsync -a "$src/" "$dst/" 2>/dev/null || { mkdir -p "$(dirname "$dst")"; cp -rf "$src" "$(dirname "$dst")/"; }
}

case "$ACTION" in
  save)
    BIN="$ENGINE_DIR/build-linux/custom_engine"
    [ -x "$BIN" ] || { echo "[prebuilt] FATAL: no binary at $BIN — run colab_setup.sh first."; exit 1; }
    [ -d "$ENGINE_DIR/third_party/$ORT_PKG" ] || { echo "[prebuilt] FATAL: ORT pkg missing: third_party/$ORT_PKG"; exit 1; }
    mkdir -p "$FZ_CACHE/build-linux"
    cp -f "$BIN" "$FZ_CACHE/build-linux/custom_engine"
    _copy_tree "$ENGINE_DIR/third_party/$ORT_PKG" "$FZ_CACHE/third_party/$ORT_PKG"
    { echo "ort_pkg=$ORT_PKG";
      echo "glibc=$(ldd --version 2>/dev/null | head -1)";
      echo "saved=$(date)"; } > "$FZ_CACHE/manifest.txt"
    echo "[prebuilt] SAVED -> $FZ_CACHE  (custom_engine + $ORT_PKG)."
    echo "[prebuilt] Next sessions just: bash $SCRIPT_DIR/colab_prebuilt.sh restore"
    ;;

  restore)
    [ -x "$FZ_CACHE/build-linux/custom_engine" ] || {
      echo "[prebuilt] no cache at $FZ_CACHE."
      echo "[prebuilt] Build once with colab_setup.sh, then: colab_prebuilt.sh save"; exit 1; }
    mkdir -p "$ENGINE_DIR/build-linux"
    cp -f "$FZ_CACHE/build-linux/custom_engine" "$ENGINE_DIR/build-linux/custom_engine"
    chmod +x "$ENGINE_DIR/build-linux/custom_engine"
    if [ ! -d "$ENGINE_DIR/third_party/$ORT_PKG" ]; then
      _copy_tree "$FZ_CACHE/third_party/$ORT_PKG" "$ENGINE_DIR/third_party/$ORT_PKG"
    fi
    finish_local
    ;;

  wrap)
    # "Build INTO the bundle" workflow: the binary + third_party/<ORT_PKG> are
    # already present inside this bundle (you copied them back after building,
    # or the bundle was distributed with them). No Drive cache is touched — just
    # (re)generate run.sh for THIS path, fix perms, and health-check.
    BIN="$ENGINE_DIR/build-linux/custom_engine"
    [ -x "$BIN" ] || [ -f "$BIN" ] || {
      echo "[prebuilt] no binary in bundle at $BIN."
      echo "[prebuilt] Build once (colab_setup.sh) and keep build-linux/ + third_party/ in the bundle."; exit 1; }
    [ -d "$ENGINE_DIR/third_party/$ORT_PKG" ] || \
      echo "[prebuilt] WARNING: third_party/$ORT_PKG missing in bundle — engine may not find ONNX Runtime libs."
    finish_local
    ;;

  *)
    echo "usage: colab_prebuilt.sh [save|restore|wrap]   (default: restore)"
    echo "  save    : build once, then cache binary+ORT to \$FZ_CACHE on Drive"
    echo "  restore : copy that cache back into the bundle (separate-cache workflow)"
    echo "  wrap    : binary already lives in the bundle -> just write run.sh + check"
    exit 1;;
esac
